-- AlterTable
ALTER TABLE `DELIVERIES` MODIFY `address` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `DELIVERYMEN` MODIFY `address` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `STORES` MODIFY `address` VARCHAR(191) NOT NULL DEFAULT '';
